### PR TITLE
fix handling of invalid bodies that caused run-time errors

### LINKED ISSUE #18: Boundary extraction does not strip quotes
Per https://tools.ietf.org/html/rfc2046#section-5.1.1 it is permissible and often necessary to enclose boundary strings in quotes, i.e. both the following are valid

```
Content-Type: multipart/form-data; boundary=6VDnJMUegpEalEvpihpZUgF0JbjBVVgDXb0aZQcw
Content-Type: multipart/form-data; boundary="6VDnJMUegpEalEvpihpZUgF0JbjBVVgDXb0aZQcw"
```
and should result in the boundary string `6VDnJMUegpEalEvpihpZUgF0JbjBVVgDXb0aZQcw`.

Currently, lua-multipart extracts the boundary string using this:
```
instance._boundary = match(content_type, ";%s*boundary=(%S+)")
```
which will attempt to use quotes as part of the boundary. An HTTP request like this will not parse successfully, as there are no quotes present in boundary in the body:

```
POST /test HTTP/1.1
Host: example.com
Content-Type: multipart/form-data; boundary="6VDnJMUegpEalEvpihpZUgF0JbjBVVgDXb0aZQcw"

foo

--6VDnJMUegpEalEvpihpZUgF0JbjBVVgDXb0aZQcw
Content-Type: text/plain; charset="utf-8"
Content-disposition: form-data; name="api_key"

c63211ec-2157-4c35-8c38-2d9584bbee15
--6VDnJMUegpEalEvpihpZUgF0JbjBVVgDXb0aZQcw
Content-Type: text/plain; charset="utf-8"
Content-disposition: form-data; name="username"

popuko
```

### PR DESCRIPTION
**Pull request by bungle**
There were yet another bug found in this library that caused a runtime errors on invalid multipart bodies. This PR fixes those issues. Also fixes decoding of single and double quoted boundaries.

Also fixes #18

### CODE REVIEW

File: src/multipart.lua [hunk 1]
```diff
@@ -214,7 +224,13 @@ function MultipartData.new(data, content_type)
   local instance = setmetatable({}, MultipartData)
 
   if content_type then
-    instance._boundary = match(content_type, ";%s*boundary=(%S+)")
+    local boundary = match(content_type, ";%s*boundary=(%S+)")
```
Comment (kikito) [inline src/multipart.lua:239]: I don't know how big of a deal this is, but if someone sends a malformed header which does not contain "boundary" (`multipart/form-data; limit=AaB03x`) this match will return nil and the following `if` will throw an error. You might want to consider detecting the case and returning an error here.

Comment (bungle) [reply src/multipart.lua:239]: yes, let's do that! definitely!

**Review by kikito — APPROVED** [review]
